[global]
use_syslog 1
verbose 1
logging_level 7
ts2phc.nmea_serialport /run/jankgps/ts2phc
ts2phc.nmea_baudrate 115200
leapfile /usr/share/zoneinfo/leap-seconds.list
step_threshold 1.0
first_step_threshold 0.0

[enp2s0]
ts2phc.master 0
ts2phc.pin_index 0
ts2phc.channel 0
ts2phc.extts_polarity rising
ts2phc.extts_correction 0
